openapi: 3.1.0
info:
  title: Anonymous Roulette API
  version: 0.1.0
paths:
  /api/users:
    post:
      summary: Create a user.
      requestBody:
        description: Username and password for the new user.
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                  example: johntheanon
                email:
                  type: string
                  example: johndoe@email.com
            required:
              - username
              - email
      responses:
        '200':
          description: Successfuly created a user.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
  /api/users/{user_id}:
    parameters:
      - name: "user_id"
        in: path
        required: true
        description: ID of the user.
        schema:
          type: integer
    get:
      summary: Get a user by their ID.
      responses:
        '200':
          description: Successfuly retrived a user by their ID.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
    delete:
      summary: Delete a user by their ID.
      requestBody:
        description: Password of the user.
        content:
          application/json:
            schema:
              type: object
              properties:
                password:
                  type: string
                  example: mypassword
            required:
              - password
      responses:
        '204':
          description: Successfuly deleted a user by their ID.
    patch:
      summary: Update a user by their ID.
      requestBody:
        description: User information to update.
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  example: johnthenew@update.com
                first_name:
                  type: string
                  example: Johnathan
                last_name:
                  type: string
                  example: Doeman
                birth_date:
                  type: string
                  format: date
                  example: 2002-02-02
                ethnicity:
                  type: integer
                  example: 2
                anonymous:
                  type: boolean
                  example: false
      responses:
        '204':
          description: Successfuly updated a user by their ID.
components:
  schemas:
    User:
      type: object
      properties:
        id:
          type: integer
          example: 1
        username:
          type: string
          example: johntheanon
        email:
          type: string
          example: johndoe@email.com
        profilePicture:
          type: string
          example: https://upload.wikimedia.org/wikipedia/commons/thumb/5/50/John_and_Jane_Doe_Headstones.jpg
        firstName:
          type: string
          example: John
        lastName:
          type: string
          example: Doe
        birthDate:
          type: string
          format: date
          example: 2000-01-01
        ethnicity:
          type: string
          example: African American
        anonymous:
          type: boolean
          example: true
