defmodule AnonRoulette.EventVote do
  use Ecto.Schema

  # This defines the database table for the schema
  @primary_key{:event_vote_id,:integer,autogenerated: false}
  schema "event_votes" do
    field :yes_vote, :boolean
    field :no_vote, :boolean

    belongs_to :event, AnonRoulette.Event, foreign_key :event_vote_id
    #timestamps()
  end


end
