defmodule AnonRoulette.Report do
  use Ecto.Schema

  # This defines the database table for the schema
  @primary_key{:report_id,:uuid, autogenerated: true}
  schema "reports" do
    field :reason, :string
    field :sent_date, :date

    #FK from users table
    belongs_to :sender_user, AnonRoulette.user, foreign_key :sender_id
    belongs_to :offender_user, AnonRoulette.user, foreign_key :offender_id


    #timestamps()
  end


end
