defmodule AnonRoulette.RouletteSession do
  use Ecto.Schema

  # This defines the database table for the schema
  @primary_key {:roulette_session_id, :uuid, autogenerated: true}
  schema "roulette_sessions" do

    #FK and PK for many-to-many users_roulette table
    many_to_many :users, AnonRoulette.User, joint_through: "users_roulette"

    #FK and PK for many-to-many categories_roulette table
    many_to_many :category, AnonRoulette.Category, joint_through: "categories_roulette"

    #FK for events table
    has_many :events, AnonRoulette.Event, foreign_key :roulette_session_id


    #timestamps()
  end

  # This defines changeset functions for creating and updating data

end
